DEP-81: add status check endpoint for polling client

diff --git a/run-e2e-tests.yml b/run-e2e-tests.yml
--- a/run-e2e-tests.yml
+++ b/run-e2e-tests.yml
@@ -6,17 +6,21 @@ steps:
     waitFor: ['-']
     entrypoint: 'bash'
     args: ['-c', 'docker build -f server/Dockerfile.dev -t $$ARTIFACTS/server-img-$$ENV:$SHORT_SHA server']
-    secretEnv: ['ARTIFACTS', 'ENV']
+    secretEnv:
+      - 'ARTIFACTS'
+      - 'ENV'
 
-  # Push server image
+  # Push server image to Artifact Registry
   - name: 'gcr.io/cloud-builders/docker'
     id: 'push-server'
     waitFor: ['build-server']
     entrypoint: 'bash'
     args: ['-c', 'docker push $$ARTIFACTS/server-img-$$ENV:$SHORT_SHA']
-    secretEnv: ['ARTIFACTS', 'ENV']
+    secretEnv:
+      - 'ARTIFACTS'
+      - 'ENV'
 
-  # Deploy server to Cloud Run, tag as a test revision (receiving no traffic)
+  # Deploy server as a test revision (no traffic)
   - name: 'gcr.io/cloud-builders/gcloud'
     id: 'deploy-server'
     waitFor: ['push-server']
@@ -26,6 +30,9 @@ steps:
       - |
         gcloud run deploy wtix-server-$$ENV \
         --image $$ARTIFACTS/server-img-$$ENV:$SHORT_SHA \
+        --revision-suffix $SHORT_SHA \
+        --no-traffic \
+        --tag test \
         --region $$REGION \
         --platform managed \
         --memory $$SERVER_MEMORY \
@@ -34,8 +41,6 @@ steps:
         --allow-unauthenticated \
         --min-instances 1 \
         --max-instances 10 \
-        --no-traffic \
-        --tag test \
         --set-cloudsql-instances $$SQL_INSTANCE \
         --service-account $$SERVICE_ACCOUNT \
         --set-env-vars=\
@@ -66,6 +71,7 @@ steps:
       - 'SQL_INSTANCE'
 
   # Build client image and pass in arguments needed by React at build time
+  # TODO: build without Playwright, use official Playwright image for testing
   - name: 'gcr.io/cloud-builders/docker'
     id: 'build-client'
     waitFor: ['-']
@@ -75,8 +81,8 @@ steps:
       - |
         docker build -f client/Dockerfile.dev -t $$ARTIFACTS/client-img-$$ENV:$SHORT_SHA client \
         --build-arg AUTH0_CLIENT_SECRET=$$AUTH0_CLIENT_SECRET \
-        --build-arg REACT_APP_API_1_URL=$$REACT_APP_API_1_URL \
-        --build-arg REACT_APP_API_2_URL=$$REACT_APP_API_2_URL \
+        --build-arg REACT_APP_API_1_URL=$$SERVER_REVISION/api/1 \
+        --build-arg REACT_APP_API_2_URL=$$SERVER_REVISION/api/2 \
         --build-arg REACT_APP_AUTH0_AUDIENCE=$$SERVER_REVISION \
         --build-arg REACT_APP_AUTH0_CLIENT_ID=$$AUTH0_CLIENT_ID \
         --build-arg REACT_APP_AUTH0_URL=$$AUTH0_URL \
@@ -89,8 +95,6 @@ steps:
       - 'AUTH0_URL'
       - 'ENV'
       - 'PUBLIC_STRIPE_KEY'
-      - 'REACT_APP_API_1_URL'
-      - 'REACT_APP_API_2_URL'
       - 'SERVER_REVISION'
 
   # Push client image to Artifact Registry
@@ -103,7 +107,7 @@ steps:
       - 'ARTIFACTS'
       - 'ENV'
 
-  # Deploy client to Cloud Run, tag as a test revision (receiving no traffic)
+  # Deploy client as test revision (no traffic)
   - name: 'gcr.io/cloud-builders/gcloud'
     id: 'deploy-client'
     waitFor: ['push-client']
@@ -113,6 +117,9 @@ steps:
       - |
         gcloud run deploy wtix-client-$$ENV \
         --image $$ARTIFACTS/client-img-$$ENV:$SHORT_SHA \
+        --revision-suffix $SHORT_SHA \
+        --no-traffic \
+        --tag test \
         --region $$REGION \
         --platform managed \
         --memory $$CLIENT_MEMORY \
@@ -121,8 +128,7 @@ steps:
         --allow-unauthenticated \
         --min-instances 1 \
         --max-instances 10 \
-        --no-traffic \
-        --tag test \
+        --service-account $$SERVICE_ACCOUNT \
         --set-env-vars=\
         ENV=$$ENV, \
         --set-secrets=\
@@ -136,17 +142,47 @@ steps:
       - 'REGION'
       - 'SERVICE_ACCOUNT'
 
-  # Wait 3.5 minutes for client to load all content
-  - name: 'ubuntu'
-    id: 'wait-for-client'
+  # Use Playwright to load test client
+  - name: 'mcr.microsoft.com/playwright:latest'
+    id: 'load-client'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
-        echo "Waiting for client to start up..."
-        sleep 210
-    
+        playwright eval --browser-type=chromium $$CLIENT_REVISION \
+        -- 'await page.goto(process.argv[2]);'
+    secretEnv:
+      - 'CLIENT_REVISION'
+
+  # Poll the /status endpoint for 5 minutes and check for readiness
+  - name: 'curlimages/curl'
+    id: 'wait-for-client'
+    entrypoint: 'sh'
+    args:
+      - '-c'
+      - |
+        statusURL=$$SERVER_REVISION/api/2/status
+        maxRetries=30
+        for i in $$(seq 1 $$maxRetries); do
+          response=$$(curl -s -o /dev/null -w "%{http_code}" $$statusURL) 
+          if [ "$$response" == "200" ]; then
+            echo "Client is ready. Running tests..."
+            exit 0
+          else
+            echo "Client is not ready: $$response. Attempt $$i/$$maxRetries."
+            echo "Retrying in 10 seconds..."
+            sleep 10
+          fi
+        done
+
+        echo "Client did not spin up in time. Exiting..."
+        exit 1
+    secretEnv:
+      - 'ENV'
+      - 'SERVER_REVISION'
+
   # Use client image to run E2E tests on test revision
+  # TODO: pull official Playwright image, run tests using that instead
   - name: 'gcr.io/cloud-builders/docker'
     id: 'run-e2e-tests'
     entrypoint: 'bash'
@@ -167,7 +203,8 @@ steps:
       - 'TEST_EMAIL'
       - 'TEST_PASSWORD'
     
-  # Delete test revisions whether tests pass or fail
+  # Delete server and client if all tests pass
+  # TODO: run this step whether tests pass or fail
   - name: 'gcr.io/cloud-builders/gcloud'
     id: 'clean-up'
     entrypoint: 'bash'
@@ -176,13 +213,8 @@ steps:
       - |
         echo "Deleting test revisions..."
 
-        TEST_CLIENT=$$(gcloud run services describe wtix-client-$$ENV \
-        --format="value(status.traffic[?tag='test'].revision)")
-        TEST_SERVER=$$(gcloud run services describe wtix-server-$$ENV \
-        --format="value(status.traffic[?tag='test'].revision)")
-
-        gcloud run revisions delete $${TEST_CLIENT}
-        gcloud run revisions delete $${TEST_SERVER}
+        gcloud run revisions delete wtix-client-$$ENV-$SHORT_SHA
+        gcloud run revisions delete wtix-server-$$ENV-$SHORT_SHA
 
         echo "Test revisions deleted."
     secretEnv:
@@ -209,10 +241,6 @@ availableSecrets:
     env: 'ENV'
   - versionName: projects/$PROJECT_ID/secrets/PUBLIC_STRIPE_KEY/versions/$_ENV
     env: 'PUBLIC_STRIPE_KEY'
-  - versionName: projects/$PROJECT_ID/secrets/REACT_APP_API_1_URL/versions/$_ENV
-    env: 'REACT_APP_API_1_URL'
-  - versionName: projects/$PROJECT_ID/secrets/REACT_APP_API_2_URL/versions/$_ENV
-    env: 'REACT_APP_API_2_URL'
   - versionName: projects/$PROJECT_ID/secrets/REGION/versions/$_ENV
     env: 'REGION'
   - versionName: projects/$PROJECT_ID/secrets/SERVER_CPU/versions/$_ENV
@@ -229,3 +257,4 @@ availableSecrets:
     env: 'TEST_EMAIL'
   - versionName: projects/$PROJECT_ID/secrets/TEST_PASSWORD/versions/$_ENV
     env: 'TEST_PASSWORD'
+
